In [1]:
import pandas as pd
def load_data():
    url = "https://it.wikipedia.org/wiki/NASDAQ-100"
    html = pd.read_html(url, header=0)
    df = html[0]
    return df

df = load_data()
df

       #             Company Simbolo    Peso   Prezzo    Chg     % Chg
0      1           Apple Inc    AAPL  11.390   237.69   1.28   (0.54%)
1      2      Microsoft Corp    MSFT  11.185   138.21   0.80   (0.58%)
2      3      Amazon.com Inc    AMZN   9.270  1767.79  10.28   (0.58%)
3      4        Facebook Inc      FB   4.811   186.88   1.03   (0.55%)
4      5        Alphabet Inc    GOOG   4.647  1252.00   6.51   (0.52%)
..   ...                 ...     ...     ...      ...    ...       ...
98    99            Fox Corp    FOXA   0.132    32.27   0.06   (0.19%)
99   100            Mylan NV     MYL   0.112    18.25  -0.08  (-0.44%)
100  101    Henry Schein Inc    HSIC   0.110    62.81   0.00   (0.00%)
101  102            Fox Corp     FOX   0.098    31.60   0.08   (0.24%)
102  103  Liberty Global PLC   LBTYA   0.063    25.80   0.00   (0.00%)

[103 rows x 7 columns]